### ISSUE TITLE
Link to the charter from w3c community page?

### ISSUE THREAD

**Issue by dj2** [fedidcg/admin#1]
It took a bit of digging to find the charter files. Would it be possible to update the https://www.w3.org/community/fed-id/ page with links to https://fedidcg.github.io/ and https://fedidcg.github.io/charter into as an announcement or something? I found the w3c page through a google search and the github.io page by looking through the repo.

**Comment by wseltzer** [comment]
thanks @hlflanagan for the update

**Comment by dj2** [comment]
Looks great. Thank you.
